### ISSUE TITLE
DKIM setup, doesn't stick

### ISSUE THREAD

**Issue by LordMike** [bambocher/docker-exim-relay#1]
Hey,

Great descriptions and all, and I think I've followed all steps, but I seem unable to make a setup that send DKIM signed mails. I've overcome the initial issue with lacking permissions on the volume (exim ran as uid 100, gid 101), and have gotten the key generated (and published a DKIM key in the DNS), at: `dkim._domainkey.kbh.mbwarez.dk`

My Compose file is as follows:

```
smtp:
  image: bambucha/exim-relay
  user: exim
  ports:
    - 192.168.1.11:25:25
  volumes:
    - /mnt/systems/configs/mailserver/keys:/dkim
  hostname: mail.kbh.mbwarez.dk
  environment:
    - RELAY_FROM_HOSTS=10.0.0.0/8:172.16.0.0/12:192.168.0.0/16
    - DKIM_KEY_SIZE=1024
    - DKIM_SELECTOR=dkim
    - DKIM_SIGN_HEADERS=Date:From:To:Subject:Message-ID
    - DKIM_DOMAINS=kbh.mbwarez.dk
  restart: always
```

My log says the following:
```
# docker-compose up
Starting mailserver_smtp_1
Attaching to mailserver_smtp_1
smtp_1 | 2017-01-10 00:16:29 exim 4.87 daemon started: pid=5, -q15m, listening for SMTP on port 25 (IPv4)
smtp_1 | 2017-01-10 00:16:33 1cQk77-000007-7z <= test@kbh.mbwarez.dk H=(MB-WIN10) [192.168.1.100] P=esmtp S=326 T="Hi" for michael@mbwarez.dk
smtp_1 | 2017-01-10 00:16:34 1cQk77-000007-7z => michael@mbwarez.dk F=<test@kbh.mbwarez.dk> R=dnslookup T=remote_smtp H=aspmx.l.google.com [108.177.96.27] C="250 2.0.0 OK 1484007394 l5si123444wju.6 - gsmtp"
smtp_1 | 2017-01-10 00:16:34 1cQk77-000007-7z Completed
^CGracefully stopping... (press Ctrl+C again to force)
Stopping mailserver_smtp_1 ... done
```

I send the actual mail with a powershell cmdlet from a windows client (as seen in the logs, it all arrives as expected).

What am I doing wrong?

Note: The mails do arrive at my Gmail inbox, the SPF validates, but the mail is with no trace of DKIM signatures.
